name:       dynamic-pipeline
version:    0.1.0.0
category:   Data,Data Flow,Pipes
author:     Juan Pablo Royo Sales
maintainer: juanpablo.royo@gmail.com
copyright:  Copyright (C) 2021 Juan Pablo Royo Sales
license:    BSD3
github:     jproyo/dynamic-pipeline

extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -fno-warn-partial-type-signatures
  - -fconstraint-solver-iterations=0
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-top-binds
  - -fno-warn-deprecations
  - -fno-warn-orphans

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PolyKinds
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies

dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring
  - containers
  - exceptions
  - HList
  - lens
  - relude >= 1.0.0.0
  - unagi-chan
  - trifecta

library:
  source-dirs: src
  exposed-modules:
    - DynamicPipeline
  when:
    - condition: false
      other-modules: Paths_connected_comp

executables:
  repeated-example:
    source-dirs:
      examples
    main:
      Main.hs
    dependencies:
      - dynamic-pipeline
      - async
      - HList
      - trifecta
    ghc-options:
      - -threaded
      - -O3
      - -rtsopts
      - -with-rtsopts=-N

tests:
  conn-comp-tests:
    main: Spec.hs
    source-dirs:
      - test
    build-tools:
      - hspec-discover
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      # TODO remove no warnings
      - -Wno-unused-local-binds
      - -Wno-unused-matches
    dependencies:
      - dynamic-pipeline
      - hspec == 2.*
      - QuickCheck
      - relude >= 1.0.0.0
      

